export const healthTips = [
  "🥑 Avocados are packed with healthy fats that help your body absorb nutrients!",
  "💧 Drink water before meals to help control portion sizes naturally.",
  "🥗 Eating colorful vegetables ensures you get a variety of nutrients.",
  "🏃 Just 10 minutes of movement can boost your mood and energy!",
  "😴 Quality sleep is just as important as diet and exercise for health.",
  "🥜 Nuts make a perfect snack - they're filling and heart-healthy!",
  "🍎 An apple a day really does help keep the doctor away!",
  "🧘 Taking deep breaths can reduce stress and improve digestion.",
  "🥦 Broccoli is a superfood packed with vitamins C and K!",
  "🚶 Walking after meals helps regulate blood sugar levels.",
  "🫐 Berries are antioxidant powerhouses that support brain health.",
  "🥛 Calcium from dairy or fortified foods keeps your bones strong.",
  "🌞 Morning sunlight helps regulate your sleep-wake cycle.",
  "🥕 Carrots are great for eye health thanks to beta-carotene!",
  "🍵 Green tea contains antioxidants that may boost metabolism.",
  "🥚 Eggs are a complete protein source with all essential amino acids.",
  "🧃 Limit sugary drinks - they add calories without nutrition.",
  "🥬 Leafy greens like spinach are loaded with iron and vitamins.",
  "🏋️ Strength training helps build muscle and boost metabolism.",
  "🍌 Bananas are rich in potassium, great for heart health!",
  "🥤 Staying hydrated improves focus and physical performance.",
  "🍊 Vitamin C from citrus fruits supports your immune system.",
  "🥙 Whole grains provide sustained energy throughout the day.",
  "🧠 Omega-3 fatty acids from fish support brain function.",
  "🎯 Setting small, achievable goals leads to lasting habits!",
  "🍇 Grapes contain resveratrol, which may support heart health.",
  "🥗 Meal prep on weekends makes healthy eating easier all week.",
  "🏃‍♀️ Consistency beats intensity - regular exercise is key!",
  "🥒 Cucumbers are 95% water, perfect for hydration.",
  "😊 Eating mindfully helps you enjoy food and recognize fullness.",
  "🥩 Lean proteins help build and repair body tissues.",
  "🌰 Almonds are great for heart health and weight management.",
  "🥝 Kiwis have more vitamin C than oranges!",
  "🧘‍♀️ Yoga combines physical activity with stress relief.",
  "🍠 Sweet potatoes are rich in fiber and vitamin A.",
  "💪 Protein after workouts helps muscles recover and grow.",
  "🥗 Eating breakfast kickstarts your metabolism for the day.",
  "🚴 Cycling is a low-impact cardio exercise that's easy on joints.",
  "🥜 Peanut butter provides protein and healthy fats.",
  "🌊 Swimming is a full-body workout that's gentle on the body.",
  "🥦 Steaming vegetables preserves more nutrients than boiling.",
  "🎵 Music during workouts can boost performance and motivation!",
  "🥗 Portion control is easier with smaller plates and bowls.",
  "🏃 Interval training burns more calories in less time.",
  "🥑 Healthy fats help you feel full and satisfied longer.",
  "📱 Tracking your food helps you stay aware of what you eat.",
  "🧊 Cold water may slightly boost metabolism.",
  "🥗 Eating slowly gives your brain time to register fullness.",
  "🏋️‍♀️ Rest days are crucial for muscle recovery and growth.",
  "🥤 Herbal teas can be a calorie-free way to stay hydrated."
];

export function getRandomHealthTip(): string {
  return healthTips[Math.floor(Math.random() * healthTips.length)];
}
